# fly.toml app configuration file generated for electric-datagrid on 2024-03-29T17:07:41+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'electric-datagrid'
primary_region = 'cdg'

[build]

[build.args]
  HYPERFIDDLE_DOMAIN="datagrid"

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  processes = ['app']

# Same spec as Datomic Browser
[[vm]]
  size = 'shared-cpu-8x'
  memory = '4gb'

# [processes]
#   app = "./prod.sh $VERSION"