app = "agents-dashboard"
primary_region = "ewr"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443


[[services]]
  internal_port = 8081
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 200
    soft_limit = 150
    type = "connections"

  [[services.ports]]
    # force_https = true
    handlers = ["tls", "http"]
    port = 8080

[build.args]
  HYPERFIDDLE_DOMAIN="agents"
  ENTRYPOINT="prod-with-agents"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '2gb'

# NO_COLOR=1 fly deploy --config src/agents/fly.toml --remote-only --build-only

# fly scale vm shared-cpu-8x --config src/agents/fly.toml
# fly scale show  --config src/agents/fly.toml
# fly status --config src/agents/fly.toml